services:
  open-webui:
    build:
      context: .
      dockerfile: Dockerfile.renesas
    image: gen-open-webui:latest
    container_name: open-webui
    volumes:
      - open-webui:/app/backend/data
    ports:
      - "8080:8080"  # expose port 8080
    environment:
      - 'ENABLE_OLLAMA_API=False'
      - 'WEBUI_SECRET_KEY=my_secret_webui_key'
      - 'WEBUI_NAME=Generative AI'
      - 'WEBUI_URL=http://10.210.106.4'
      - 'WEBUI_LOG_URL=http://10.210.106.4:7359'
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped

  proxy:
    image: nginx:1.25.4-alpine3.18
    container_name: open-reverse-proxy
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
      - "7380:7380"
    depends_on:
      - open-webui
    restart: unless-stopped

volumes:
  open-webui: { }