services:
  open-webui:
    image: kakazaro/open-webui:latest # pull from docker hub
    pull_policy: always # always try to pull the newest image
    container_name: open-webui
    volumes:
      - open-webui:/app/backend/data
    ports:
      - 7380:8080 # expose port 7380
    environment:
      - 'ENABLE_OLLAMA_API=False'
      - 'WEBUI_SECRET_KEY='
      - 'WEBUI_NAME=Generative AI'
      - 'WEBUI_URL=http://10.210.106.4:7380'
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped

volumes:
  open-webui: {}
