services:
  open-webui:
    image: kakazaro/open-webui:latest # pull from docker hub
    pull_policy: always # always try to pull the newest image
    container_name: open-webui
    volumes:
      - open-webui:/app/backend/data
    ports:
      - 7380:8080 # expose port 7380
    environment:
      - 'ENABLE_OLLAMA_API=False'
      - 'WEBUI_SECRET_KEY=my_secret_webui_key'
      - 'WEBUI_NAME=Generative AI'
      - 'WEBUI_URL=http://10.210.106.4:7380'
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped

  loki:
    image: grafana/loki:3.4.2
    container_name: loki
    ports:
      - "7384:3100" # Change the port mapping for Loki
    volumes:
      - ./loki-config.yml:/etc/loki/loki-config.yaml

  promtail:
    image: grafana/promtail:3.4.2
    container_name: promtail
    volumes:
      - ./promtail-config.yml:/etc/promtail/promtail-config.yaml

  open-webui-grafana:
    image: grafana/grafana:latest
    container_name: open-webui-grafana
    ports:
      - "7385:3000" # Change the port mapping for Grafana

volumes:
  open-webui: {}
#  loki-data: {}
