services:
  open-webui:
    build:
      context: .
      dockerfile: Dockerfile.renesas
    image: gen-open-webui:latest
    container_name: open-webui
    volumes:
      - open-webui:/app/backend/data
    ports:
      - 7380:8080 # expose port 7380
    environment:
      - 'ENABLE_OLLAMA_API=False'
      - 'WEBUI_SECRET_KEY=my_secret_webui_key'
      - 'WEBUI_NAME=Generative AI'
      - 'WEBUI_URL=http://10.210.106.4:7380'
      - 'WEBUI_LOG_URL=http://10.210.106.4:7359'
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped

volumes:
  open-webui: {}
